### ISSUE TITLE
[suggestion] Added more amulet slots too.

### ISSUE THREAD

**Issue by jusitnboggs** [zabi94/BringMeTheRings#2]
Can you add more amulet slots I am finding a lot of mods I am using have a fair bit of amulets?

**Comment by zabi94** [comment]
No because
A) Other types of baubles have a major inconvenience, they come in a single inventory slot in vanilla Baubles, so it's more common for them to have hardcoded slot numbers, meaning that many would crash or just not work properly. On the balancing side, many mods are balanced around the fact that only one of them can be worn at any time, so I'm not gonna mess with it. Rings are the only exception, as there are two in vanilla baubles

B) it's a lot of work
